# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 10:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstream_url', models.URLField(help_text='Required. 200 characters or fewer.', verbose_name='upstream url of HTTP service.')),
                ('method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete')], default='post', help_text='Service Supported Methods.', max_length=6, verbose_name='Service Supported Method ')),
                ('headers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Request Headers.', null=True, verbose_name='Request Headers')),
                ('dataIn', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Request payload, includes query_params, data etc.', null=True, verbose_name='Request payload')),
                ('dataOut', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Response that is returned via service.', null=True, verbose_name='Request response')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='service request time.')),
            ],
            options={
                'verbose_name': 'HTTP Service',
                'ordering': ['-id'],
                'verbose_name_plural': 'HTTP Service',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='TransactionLifeCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='id of object you want to map')),
                ('state', models.CharField(choices=[(('init',), 'Initialize'), ('processing', 'processing'), ('complete', 'complete'), ('fail', 'fail'), ('resume', 'resume'), ('restart', 'restart')], default=('init',), help_text='Task state at any given time.', max_length=20, verbose_name='current state of any task')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Task state activity create time.')),
                ('content_type', models.ForeignKey(help_text='Content Type of Object you want tyo map.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Transaction Life Cycle',
                'ordering': ['-id'],
                'verbose_name_plural': 'Transaction Life Cycle',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='TransactionStateMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='task name')),
                ('task_identifier', models.CharField(help_text='Required. 200 characters or fewer.', max_length=200, verbose_name='any unique identifier of any task')),
                ('state', models.CharField(choices=[(('init',), 'Initialize'), ('processing', 'processing'), ('complete', 'complete'), ('fail', 'fail'), ('resume', 'resume'), ('restart', 'restart')], default=('init',), help_text='Task state at any given time.', max_length=20, verbose_name='current state of any task')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Task state activity create time.')),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Task state activity modify time.')),
            ],
            options={
                'verbose_name': 'Transaction State Machine',
                'ordering': ['-id'],
                'verbose_name_plural': 'Transaction State Machine',
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='transactionlifecycle',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_machine.TransactionStateMachine', verbose_name='transaction state machine'),
        ),
    ]
