# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlifecycle',
            name='state',
            field=models.CharField(choices=[('init', 'Initialize'), ('processing', 'processing'), ('complete', 'complete'), ('fail', 'fail'), ('resume', 'resume'), ('restart', 'restart')], default='init', help_text='Task state at any given time.', max_length=20, verbose_name='current state of any task'),
        ),
        migrations.AlterField(
            model_name='transactionstatemachine',
            name='created_at',
            field=models.DateTimeField(db_index=True, verbose_name='Task state activity create time.'),
        ),
        migrations.AlterField(
            model_name='transactionstatemachine',
            name='modified_at',
            field=models.DateTimeField(db_index=True, verbose_name='Task state activity modify time.'),
        ),
        migrations.AlterField(
            model_name='transactionstatemachine',
            name='state',
            field=models.CharField(choices=[('init', 'Initialize'), ('processing', 'processing'), ('complete', 'complete'), ('fail', 'fail'), ('resume', 'resume'), ('restart', 'restart')], default='init', help_text='Task state at any given time.', max_length=20, verbose_name='current state of any task'),
        ),
    ]
