# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_machine', '0002_auto_20170315_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlifecycle',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Content Type of Object you want tyo map.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='transactionlifecycle',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='id of object you want to map'),
        ),
    ]
