# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-16 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_machine', '0003_auto_20170316_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionstatemachine',
            name='task_identifier',
            field=models.CharField(help_text='Required. 200 characters or fewer.', max_length=200, unique=True, verbose_name='any unique identifier of any task'),
        ),
    ]
